### ISSUE TITLE
Bug: Hone Claw affected with Dex and Frail

### ISSUE THREAD

**Issue by red5h4d0w** [red5h4d0w/mystery-dungeon-mod#43]
# Info about your system
- OS: any
- Mystery Dungeon mod version: v2.0-beta2

Additional information (can include other mods if you think this could be useful):

# Describe the bug in as much detail
Based on the wording for the card, the amount of block applied is based on block which changes with respect to Powers on the player. 

A proposed solution is to use the second magic Number

# Log output (can be extremely useful for crashes)
None

**Comment by Ivel54** [comment]
not a bug it's intended

**Comment by red5h4d0w** [comment]
It doesn't go well with the wording of Dexterity and Frail therefore should be changed
