### ISSUE TITLE
Bug:  Thrash numbers are inversed

### ISSUE THREAD

**Issue by Ivel54** [red5h4d0w/mystery-dungeon-mod#45]
# Info about your system
- OS:
- Mystery Dungeon mod version: Totodile beta 2.0

Additional information (can include other mods if you think this could be useful):

# Describe the bug in as much detail
Thrash need 6 atk instead of 4 and gains 4 vigor instead of 6 in the description

# Log output (can be extremely useful for crashes)

**Comment by red5h4d0w** [comment]
fixed in f5c53d749050564ca0501b0105f02f01f527bb13
