### ISSUE TITLE
Bug: Sheer force power description f ups

### ISSUE THREAD

**Issue by Ivel54** [red5h4d0w/mystery-dungeon-mod#46]
# Info about your system
- OS:
- Mystery Dungeon mod version:

Additional information (can include other mods if you think this could be useful):

# Describe the bug in as much detail
sheer force ppower description says 211 instead of 21 and 1

# Log output (can be extremely useful for crashes)

**Comment by red5h4d0w** [comment]
fixed in f5c53d749050564ca0501b0105f02f01f527bb13
