### ISSUE TITLE
Bug:  Water Pulse dmg scaling

### ISSUE THREAD

**Issue by Ivel54** [red5h4d0w/mystery-dungeon-mod#48]
# Info about your system
- OS:
- Mystery Dungeon mod version:

Additional information (can include other mods if you think this could be useful):

# Describe the bug in as much detail
When having additional dmg water pulse scale his smg like a multi hit

# Log output (can be extremely useful for crashes)

**Comment by red5h4d0w** [comment]
fixed in 27bb1b70343268eb16226010a72a305fd6859f30
