### ISSUE TITLE
Bug: Victoire carabaffe et raichu?

### ISSUE THREAD

**Issue by Ivel54** [red5h4d0w/mystery-dungeon-mod#51]
# Info about your system
- OS:
- Mystery Dungeon mod version:

Additional information (can include other mods if you think this could be useful):

# Describe the bug in as much detail
engrod est-ceq que wartortle évolue

# Log output (can be extremely useful for crashes)

**Comment by red5h4d0w** [comment]
According to http://scarlet-tales-studio.com/graphs/game/432 , the player was playing on the Steam Version which has this issue.

Should be fixed in 2.0
