### ISSUE TITLE
Chikorita art that could be improved

### ISSUE THREAD

**Issue by red5h4d0w** [red5h4d0w/mystery-dungeon-mod#79]
- [ ] Razor Leaf could move away from bulbasaur
- [ ] Same with Tackle
- [ ] Growl could use something else
- [ ] Worry Seed 
- [ ] Vine Whip
- [ ] Petal Dance
- [ ] Solar Beam
- [ ] Remove Ash from confide or change iamge

**Comment by Ivel54** [comment]
you did it be proud
